/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function init(): void
export declare function install(): void
export declare function runHook(hookName: string, args: Array<string>): void
export declare function autoCommit(commit: boolean): Promise<void>
